### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by paragasu** [phisoft/phiaroma-web#7]
[PHI AROMA Logo Description.pdf](https://github.com/phisoft/phiaroma-web/files/7593081/PHI.AROMA.Logo.Description.pdf)

**Comment by niksyarul** [comment]
Desktop view:
![Screenshot 2021-11-26 at 10-27-29 Phi Aroma - The Scent of Borneo](https://user-images.githubusercontent.com/90664417/143518544-8a2348ff-b176-4560-8ace-7abe68f96226.png)

Mobile View:
![Screenshot 2021-11-26 at 10-39-15 Phi Aroma - The Scent of Borneo](https://user-images.githubusercontent.com/90664417/143518573-9dfa6b50-aef7-4058-bc55-1712c66c59da.png)
@paragasu
