### ISSUE TITLE
Replace with ig embeded update

### ISSUE THREAD

**Issue by paragasu** [phisoft/phiaroma-web#8]
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/27353/143185972-b720bf8e-3e52-4974-b0b8-328f2f6d6204.png">

**Comment by niksyarul** [comment]
Choose this widget because it is one of few that did not need to login to the client's Instagram account
![Screenshot 2021-11-26 at 10-27-56 Phi Aroma - The Scent of Borneo](https://user-images.githubusercontent.com/90664417/143518091-2c698cfa-ac91-4332-b8f0-cbe661df52ea.png)
